static const char black[]       = "#1e2122";
static const char white[]       = "#DCD7BA";
static const char gray2[]       = "#282b2c"; // unfocused window border
static const char gray3[]       = "#5d6061";
static const char gray4[]       = "#282b2c";
static const char blue[]        = "#2D4F67";  // focused window border
static const char green[]       = "#76946A";
static const char red[]         = "#C34043";
static const char orange[]      = "#d6b676";
static const char yellow[]      = "#DCA561";
static const char pink[]        = "#D27E99";
static const char col_borderbar[]  = "#1e2122"; // inner border
